spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spotme}
    username: ${SPRING_DATASOURCE_USERNAME:spotme}
    password: ${SPRING_DATASOURCE_PASSWORD:spotme}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info        # keep it simple first
grpc:
  server:
    port: 9090

spotme:
  grpc:
    client:
      host: localhost
      port: 9090
      plaintext: true
